# Generated by Django 5.0.3 on 2024-03-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
                ('no_of_modules', models.IntegerField()),
                ('scheme', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('max_time', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('focus_area', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
