# Generated by Django 5.0.3 on 2024-03-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='focus_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='max_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
