# Generated by Django 5.0.3 on 2024-05-12 19:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assignement_2_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='assignment_1_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='no_marked_as_difficult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='no_marked_as_easy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='no_marked_as_important',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
