# Generated by Django 5.0.3 on 2024-03-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='max_time',
            new_name='max_study_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='min_time',
            new_name='min_study_time',
        ),
    ]
